enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/quark/images/logo/logo.png:
    name: logo.png
    type: image/png
    size: 24287
    path: user/themes/quark/images/logo/logo.png
custom_logo_mobile:
  user/themes/quark/images/logo/logo2.png:
    name: logo2.png
    type: image/png
    size: 6241
    path: user/themes/quark/images/logo/logo2.png
